Repository pjechris/SimpleHTTP, pull requests merged in 2022-10, with the labels that each got.

#15 feat(request): [#11] Rename Endpoint -> Path
  README.md
  Sources/SimpleHTTP/Request/Endpoint.swift
  Sources/SimpleHTTP/Request/Path.swift
  Sources/SimpleHTTP/Request/Request.swift
  Sources/SimpleHTTP/Request/URL+Request.swift
  Sources/SimpleHTTPFoundation/Foundation/URLRequest/URLRequest+URL.swift
  Tests/SimpleHTTPFoundationTests/Foundation/URLRequest/URLRequestTests+URL.swift
  Tests/SimpleHTTPFoundationTests/Foundation/URLRequest/URLRequestsTests+Encode.swift
  Tests/SimpleHTTPFoundationTests/Foundation/URLResponseValidateTests.swift
  Tests/SimpleHTTPTests/Request/RequestTests.swift
  Tests/SimpleHTTPTests/Session/SessionTests.swift
Labels: enhancement

#16 fix(foundation): Make Authorization header available
  Sources/SimpleHTTPFoundation/HTTP/HTTPHeader.swift
Labels: bug

#17 fix(foundation): Fixed crash in URLSession.data(for:)
  Sources/SimpleHTTPFoundation/Foundation/URLSession+Async.swift
Labels: bug

#18 Add swift-format file
  .swift-format
  Package.swift
Labels: hacktoberfest-accepted
